archive:
  format: tar.gz
builds:
  - main: ./
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
git:
  short_hash: true
