name: "bulk"
version: "0.0.8"
usage: "Load or Save Helm Releases"
description: |-
  Load or Save Helm Releases from File to Cluster, or Cluster to File, respectively
command: "$HOME/go/src/github.com/ovotech/helm-bulk/helm-bulk"

hooks:
  install: "$HOME/go/src/github.com/ovotech/helm-bulk/scripts/install.sh"
  update: "$HOME/go/src/github.com/ovotech/helm-bulk/scripts/install.sh"
