name: "bulk"
version: "0.0.1"
usage: "Load or Save Helm Releases
description: |-
  Load or Save Helm Releases from File to Cluster, or Cluster to File, respectively
command: "$HELM_PLUGIN_DIR/bin/helm-bulk"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
