version: 2
jobs:
  goreleaser:
    working_directory: /go/src/github.com/ovotech/helm-bulk

    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      - run:
           name: goreleaser
           command: |
             export GITHUB_TOKEN=$GITHUB
             curl -sL https://git.io/goreleaser | bash
    filters:
      tags:
        only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      branches:
        ignore: /.*/

workflows:
  version: 2
  goreleaser_pipeline:
    jobs:
      - goreleaser:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
